In [1]:
import numpy as np
import pandas as pd


In [2]:
s1 = pd.Series([2,4,6], index=['a','b','c'])
s1 = pd.Series([1,3,5], index=['b','c','d'])

In [3]:
s1

b    1
c    3
d    5
dtype: int64

In [4]:
s3.add(s4,fill_value=0)

NameError: name 's3' is not defined

In [14]:
import numpy as np

np.random.seed(0)
arr = np.random.randint(10, size=(3, 4))
arr


array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [15]:
arr[0]

array([5, 0, 3, 3], dtype=int32)

In [16]:
arr-arr[0]

array([[ 0,  0,  0,  0],
       [ 2,  9,  0,  2],
       [-3,  4,  4,  3]], dtype=int32)

In [17]:
df = pd.DataFrame(arr,columns=['P','Q','M','N'])
print("df:\n", df)

df:
    P  Q  M  N
0  5  0  3  3
1  7  9  3  5
2  2  4  7  6


In [18]:
df.iloc[0]

P    5
Q    0
M    3
N    3
Name: 0, dtype: int32

In [19]:
df.iloc[0].index

Index(['P', 'Q', 'M', 'N'], dtype='object')

In [21]:
df.columns

Index(['P', 'Q', 'M', 'N'], dtype='object')

In [23]:
df.iloc[0].index==df.columns

array([ True,  True,  True,  True])

In [24]:
df.iloc[0].name

0