In [1]:
import numpy as np
np.__version__

'2.3.3'

In [1]:
import numpy as np  
import sys  

S = list(range(1000)) 
items_S= sys.getsizeof(S) 
print("Kích thước mỗi phẫn tử trong List tính theo bytes: ",items_S) 
S_size = items_S*len(S) 
print("Kích thước của toàn bộ List tính theo bytes: ",S_size) 
D= np.arange(1000)  
print("Kích thước mỗi phần tử của mảng Numpy theo bytes: ",D.itemsize) 
array_size=D.itemsize*D.size 

print("Kích thước của toàn bộ mảng Numpy array in bytes: ",array_size) 
print(f"Tỷ lệ (list/array): {S_size / array_size:.2f}")

Kích thước mỗi phẫn tử trong List tính theo bytes:  8056
Kích thước của toàn bộ List tính theo bytes:  8056000
Kích thước mỗi phần tử của mảng Numpy theo bytes:  8
Kích thước của toàn bộ mảng Numpy array in bytes:  8000
Tỷ lệ (list/array): 1007.00


In [7]:
tong = 1
for i in range(100):
    tong += i

print(tong)

4951


In [12]:
arr = np.array([1.5, 2.7, 3.2])
arr
arr.dtype

arr_int = arr.astype(np.int32)
print(arr_int, arr_int.dtype)

print(arr, arr.dtype)

[1 2 3] int32
[1.5 2.7 3.2] float64


In [13]:
import numpy as np 
# Tạo mảng chứa 5 giá trị từ 0 đến 10 (gồm giá trị kết thúc) 
arr_1 = np.linspace(0, 10, 5) 
print(arr_1)

[ 0.   2.5  5.   7.5 10. ]


In [14]:
arr_2 = np.linspace(0, 1, 10, endpoint=False) 
print(arr_2) 

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [15]:
arr_3, step = np.linspace(1, 10, 100, retstep=True) 
print(arr_3) 
print("Step size:", step) 

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [16]:
import numpy as np 
# Tạo mảng gồm 5 phần tử từ 0 đến 10 với kiểu dữ liệu là float 
arr_4 = np.linspace(0, 10, num=5, dtype=float) 
print(arr_4)  
print(arr_4.dtype) 

[ 0.   2.5  5.   7.5 10. ]
float64


In [17]:
import numpy as np 
# Tạo môt mảng 1 chiều gồm 5 giá trị ngẫu nhiên từ phân phối đều 
#trong khoảng từ 0 đến 1 
arr_5 = np.random.random(5) 
print(arr_5) 

[0.0829397  0.56866177 0.78602003 0.12519865 0.77078106]


In [18]:
import numpy as np 
# Tạo môt mảng 100 giá trị ngẫu nhiên từ phân phối chuẩn với # trung bình 0 và độ lệch chuẩn là 1. 
arr_6 = np.random.normal(loc=0.0, scale=1.0, size=100) 
print(arr_6) 

[ 2.96171682 -0.72235951 -1.50961775 -0.28384315 -1.28312101 -0.40718982
 -0.0714777  -0.73818173  1.07286786 -0.42382711  0.10478962 -0.17063128
  2.42957452  0.30704074 -0.66032109 -1.63616098 -0.07666608  0.41861999
  0.16759938  0.39636048  0.12345838 -0.07132786  0.35604413  1.04772389
  1.01062851 -0.16973541  0.4634705  -1.78375387 -0.38354665  0.10919765
 -0.25727781  0.82241633 -0.3092033   1.41588386  0.15671254  0.76485766
  0.71888785  0.51838357  1.90073088 -0.5404465  -1.06756456  1.277733
  1.66150218 -1.07571537 -0.0805049   0.16684809 -0.57601324  1.84407052
 -0.40419866 -0.99359558  0.56310769  1.19016468 -0.52891178  0.78216175
  0.00486089  0.95737442 -0.76919333 -0.7602966  -0.6356213  -1.40993871
 -1.34760959 -0.58769101 -0.6406657  -1.78766404 -0.55063386 -0.82990594
 -0.36001671 -0.10883438  0.71184633 -1.0778965  -0.64815073 -0.61404705
  0.0690064   0.76562479  0.88028787 -1.65154534  0.77197238 -0.26168431
  1.72536104  1.0651753  -0.10895713 -1.85064322 -0.0

In [19]:
import numpy as np

arr = np.array ([[1,2,31], [4,5,6]]) # shape=(2,3)
print("Số chiều của máng là:", arr.ndim) 
print("Kích thước của mảng là:", arr. shape) 
print( "Tổng số phần tử trong mắng là:", arr.size) 
print ("Kiểu dữ liệu của các phần tử trong mảng là:", arr.dtype) 
print("Kích thước theo (byte) của mỗi phần tứ trong mảng là:", arr.itemsize) 
print( "Tổng kích thước theo (byte) của mảng là:", arr.nbytes)
# BỔ SUNG:
print ("Strides (bước nhảy bộ nhớ) là:", arr.strides)
 # Ví dụ theo trục (axis):
print("Tổng theo trục 0 (theo cột):", arr.sum(axis=0)) # [1+4, 2+5, 3+6]
print("Tổng theo trục 1 (theo hàng):", arr. sum(axis=1)) # [1+2+3, 4+5+6]

Số chiều của máng là: 2
Kích thước của mảng là: (2, 3)
Tổng số phần tử trong mắng là: 6
Kiểu dữ liệu của các phần tử trong mảng là: int64
Kích thước theo (byte) của mỗi phần tứ trong mảng là: 8
Tổng kích thước theo (byte) của mảng là: 48
Strides (bước nhảy bộ nhớ) là: (24, 8)
Tổng theo trục 0 (theo cột): [ 5  7 37]
Tổng theo trục 1 (theo hàng): [34 15]


In [23]:
import numpy as np 
arr_a = np.array([[1,2,3,4], 
                 [5,6,7,8], 
                 [9,10,11,12]]) 
np.sum(arr_a) 

np.int64(78)

In [21]:
np.sum(arr_a,axis=0) 

array([15, 18, 21, 24])

In [ ]:

np.sum(arr_a, axis=1) 

array([10, 26, 42])

In [27]:
import numpy as np 
B=np.array([[1,2,3],[4,5,6],[7,8,9]]) 
B[1,2]  

np.int64(6)

In [26]:
B[2,-1] 

np.int64(9)

In [28]:
B[2,0]   

np.int64(7)

In [29]:
B[0,0]=0                #Chỉnh sửa giá trị ở dòng 0, cột 0 thành 0 
np.array(B) 

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
import numpy as np 
A=np.arange(10) 
A 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
A[:5]  

array([0, 1, 2, 3, 4])

In [33]:
A[4:7]

array([4, 5, 6])

In [34]:
A[5:]

array([5, 6, 7, 8, 9])

In [35]:
A[3::1]

array([3, 4, 5, 6, 7, 8, 9])

In [36]:
A[-3::1]

array([7, 8, 9])