In [1]:
import numpy as np 
#Mảng đích để lưu trữ kết quả 
output=np.zeros((3,3)) 
#Mảng nguồn arr1, arr2 
arr1=np.array([1,2,3]) 
arr2=np.array([4,5,6]) 
#Thực hiện phép cộng và lưu trữ kết quả vào mảng đích output 
np.add(arr1,arr2, out=output) 
#In kết quả 
print(output)

[[5. 7. 9.]
 [5. 7. 9.]
 [5. 7. 9.]]
