In [1]:
import numpy as np
arr = np.arange(16).reshape(4, 4) 
print("Mảng gốc ban đầu:\n arr = ", arr) 
  
#Lấy các phần tử arr[3, 1], arr[3, 2] và arr[3, 3] 
sub_arr = arr[3, [1, 2, 3]] 
print("Mảng con: sub_arr = ", sub_arr) 

Mảng gốc ban đầu:
 arr =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Mảng con: sub_arr =  [13 14 15]


In [2]:
# Lấy tất cả các phần tử nằm tại hàng >= 1 và các cột = 1, 2, 3 tương ứng 
sub_arr = arr[1:, [1, 2, 3]] 
print("Mảng con sub_arr:\n", sub_arr)

Mảng con sub_arr:
 [[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [3]:
#Fancy Indexing và masks 
arr=np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]]) 
 
masks=arr[0,:]%2 == 0 #Lấy hàng 0, chia các phần tử tương ứng  1,2,3 cho 2,  
print("masks:",masks) #Kết quả là mảng [Flase True False] 
 
sub_arr=arr[:,masks]  # Kết hợp Fancy indexing và mask, dấu ':' ở vị trí hàng 
                                                            # cho biết lấy toàn bộ các hàng của mảng,  
                                                            # chỉ mục cột là masks, chỉ có 1 phần tử True ở vị trí 1 
                                                            # Vì vậy chỉ lấy cột có chỉ mục 1, tức cột 1 
print("Mảng con mới: \n", sub_arr)

masks: [False  True False]
Mảng con mới: 
 [[2]
 [5]
 [8]]
