In [1]:
import numpy as np 
arr1 = np.array([0,1,2]) 
arr2 = np.array([5,5,5]) 
arr1 + arr2 

array([5, 6, 7])

VD3.4.2.2

In [3]:
import numpy as np 
arr1 = np.array([0,1,2]) 
arr1 + 5

array([5, 6, 7])

VD3.4.4.3

In [1]:
import numpy as np 
arr = np.array([0,1,2]) 
arr

array([0, 1, 2])

In [2]:
M=np.ones((3,3)) 
M 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
arr + M

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])