In [1]:
import numpy as np 
A=np.arange(10) 
A 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
A[:5] 

array([0, 1, 2, 3, 4])

In [3]:
A[5:] 

array([5, 6, 7, 8, 9])

In [4]:
A[4:7] 

array([4, 5, 6])