In [ ]:
import numpy as np 
# Tạo mảng 2 chiều 3x3 
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]]) 
# Lấy view mới chỉ chứa 2 dòng và 2 cột của mảng gốc 
arr_view = arr_2d[:2, :2].view() 
print(arr_view) 

[[1 2]
 [4 5]]


In [2]:

arr_view[0, 0] = 100 #Chỉnh sửa phần tử ở dòng 0, cột 0 thành 10. 
print(arr_view) 

[[100   2]
 [  4   5]]


In [3]:
print("Mảng gốc sau khi thay đổi giá trị trong view:") 
print(arr_2d)  

Mảng gốc sau khi thay đổi giá trị trong view:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


VD3.3.3.2

In [3]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
sub_arr=arr[:2,:2] #slicing mảng con lấy 2 dòng, 2 cột của mảng arr 
print(sub_arr)     #in mảng con arr_con vừa được slicing

[[1 2]
 [4 5]]


In [4]:
sub_arr[0,0]=10  #Chỉnh sửa phần tử ở dòng 0, cột 0 của mảng con thành 10. 
print(sub_arr)  #in ra mảng con sau khi chỉnh sửa.

[[10  2]
 [ 4  5]]


In [5]:
print(arr)  

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


VD3.3.3.3

In [6]:
sub_arr_copy=arr[:2,:2].copy()  #Thêm phương thức copy(). 
print(sub_arr_copy)     #in mảng con vừa được copy.

[[10  2]
 [ 4  5]]


In [8]:
sub_arr_copy[0,0]=10    #sửa phần tử ở dòng 0, cột 0 của mảng 
# copy thành 10. 
print(sub_arr_copy) 

[[10  2]
 [ 4  5]]


In [9]:
print(arr) 

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


VD3.3.3.4

In [10]:
arr=np.arange(1,10)            #Tạo mảng một chiều arr có 9 phần tử từ 1-9 
grid= arr.reshape((3,3))#chuyển đổi mảng arr thành mảng grid, 3x3 
grid 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

VD3.3.3.5


In [11]:
x = np.array([1, 2, 3]) 
x.reshape((1, 3)) #tạo ma trận hàng thông qua reshape.

array([[1, 2, 3]])

In [12]:
x[np.newaxis, :]  #Tạo ma trận hàng (thêm trục dọc/thêm hàng) thông qua newaxis.

array([[1, 2, 3]])

In [14]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [15]:
x[:,np.newaxis]    #(thêm trục ngang /thêm cột) thông qua newaxis

array([[1],
       [2],
       [3]])