In [1]:
import numpy as np 
arr1 = np.arange(3) 
arr2=np.arange(3)[:,np.newaxis] 
#np.newaxis sử dụng để cho biết một chiều mới được thêm vào 
print(arr1) 
print(arr2) 

[0 1 2]
[[0]
 [1]
 [2]]


In [2]:
arr1 + arr2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])